### ISSUE TITLE
grafana error

### ISSUE THREAD

**Issue by T-TRz879** [mulbc/gosbench#28]
how can i deal with it?
<img width="1136" alt="image" src="https://github.com/mulbc/gosbench/assets/50860504/7da66be3-784a-46ae-95d6-50be1ffc62d4">

grafana compose.yml
```
  grafana:
   image: grafana/grafana
   ports:
     - 13000:3000
   volumes:
     - ./grafana/:/etc/grafana/provisioning/
     - /home/trz/hdd/monitor/grafana_data:/var/lib/grafana
       #environment:
     #- GF_INSTALL_PLUGINS=camptocamp-prometheus-alertmanager-datasource
   links:
     - prometheus:prometheus
     - alertmanager:alertmanager
   restart: always
```
